// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: api/tracker/v1/tracker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tracker_CreateBlockFunc_FullMethodName = "/helloworld.v1.tracker.Tracker/CreateBlockFunc"
	Tracker_DeletBlockFunc_FullMethodName  = "/helloworld.v1.tracker.Tracker/DeletBlockFunc"
	Tracker_UpdateBlockFunc_FullMethodName = "/helloworld.v1.tracker.Tracker/UpdateBlockFunc"
	Tracker_ListBlockFunc_FullMethodName   = "/helloworld.v1.tracker.Tracker/ListBlockFunc"
)

// TrackerClient is the client API for Tracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackerClient interface {
	CreateBlockFunc(ctx context.Context, in *CreateBlock, opts ...grpc.CallOption) (*BlockResp, error)
	DeletBlockFunc(ctx context.Context, in *DeletBlock, opts ...grpc.CallOption) (*Status, error)
	UpdateBlockFunc(ctx context.Context, in *UpdateBlock, opts ...grpc.CallOption) (*UpdateResponse, error)
	ListBlockFunc(ctx context.Context, in *GetListReq, opts ...grpc.CallOption) (Tracker_ListBlockFuncClient, error)
}

type trackerClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackerClient(cc grpc.ClientConnInterface) TrackerClient {
	return &trackerClient{cc}
}

func (c *trackerClient) CreateBlockFunc(ctx context.Context, in *CreateBlock, opts ...grpc.CallOption) (*BlockResp, error) {
	out := new(BlockResp)
	err := c.cc.Invoke(ctx, Tracker_CreateBlockFunc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerClient) DeletBlockFunc(ctx context.Context, in *DeletBlock, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Tracker_DeletBlockFunc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerClient) UpdateBlockFunc(ctx context.Context, in *UpdateBlock, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Tracker_UpdateBlockFunc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerClient) ListBlockFunc(ctx context.Context, in *GetListReq, opts ...grpc.CallOption) (Tracker_ListBlockFuncClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tracker_ServiceDesc.Streams[0], Tracker_ListBlockFunc_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &trackerListBlockFuncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tracker_ListBlockFuncClient interface {
	Recv() (*BlockResp, error)
	grpc.ClientStream
}

type trackerListBlockFuncClient struct {
	grpc.ClientStream
}

func (x *trackerListBlockFuncClient) Recv() (*BlockResp, error) {
	m := new(BlockResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrackerServer is the server API for Tracker service.
// All implementations must embed UnimplementedTrackerServer
// for forward compatibility
type TrackerServer interface {
	CreateBlockFunc(context.Context, *CreateBlock) (*BlockResp, error)
	DeletBlockFunc(context.Context, *DeletBlock) (*Status, error)
	UpdateBlockFunc(context.Context, *UpdateBlock) (*UpdateResponse, error)
	ListBlockFunc(*GetListReq, Tracker_ListBlockFuncServer) error
	mustEmbedUnimplementedTrackerServer()
}

// UnimplementedTrackerServer must be embedded to have forward compatible implementations.
type UnimplementedTrackerServer struct {
}

func (UnimplementedTrackerServer) CreateBlockFunc(context.Context, *CreateBlock) (*BlockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlockFunc not implemented")
}
func (UnimplementedTrackerServer) DeletBlockFunc(context.Context, *DeletBlock) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletBlockFunc not implemented")
}
func (UnimplementedTrackerServer) UpdateBlockFunc(context.Context, *UpdateBlock) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBlockFunc not implemented")
}
func (UnimplementedTrackerServer) ListBlockFunc(*GetListReq, Tracker_ListBlockFuncServer) error {
	return status.Errorf(codes.Unimplemented, "method ListBlockFunc not implemented")
}
func (UnimplementedTrackerServer) mustEmbedUnimplementedTrackerServer() {}

// UnsafeTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackerServer will
// result in compilation errors.
type UnsafeTrackerServer interface {
	mustEmbedUnimplementedTrackerServer()
}

func RegisterTrackerServer(s grpc.ServiceRegistrar, srv TrackerServer) {
	s.RegisterService(&Tracker_ServiceDesc, srv)
}

func _Tracker_CreateBlockFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServer).CreateBlockFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tracker_CreateBlockFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServer).CreateBlockFunc(ctx, req.(*CreateBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tracker_DeletBlockFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServer).DeletBlockFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tracker_DeletBlockFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServer).DeletBlockFunc(ctx, req.(*DeletBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tracker_UpdateBlockFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServer).UpdateBlockFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tracker_UpdateBlockFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServer).UpdateBlockFunc(ctx, req.(*UpdateBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tracker_ListBlockFunc_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetListReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrackerServer).ListBlockFunc(m, &trackerListBlockFuncServer{stream})
}

type Tracker_ListBlockFuncServer interface {
	Send(*BlockResp) error
	grpc.ServerStream
}

type trackerListBlockFuncServer struct {
	grpc.ServerStream
}

func (x *trackerListBlockFuncServer) Send(m *BlockResp) error {
	return x.ServerStream.SendMsg(m)
}

// Tracker_ServiceDesc is the grpc.ServiceDesc for Tracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.tracker.Tracker",
	HandlerType: (*TrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlockFunc",
			Handler:    _Tracker_CreateBlockFunc_Handler,
		},
		{
			MethodName: "DeletBlockFunc",
			Handler:    _Tracker_DeletBlockFunc_Handler,
		},
		{
			MethodName: "UpdateBlockFunc",
			Handler:    _Tracker_UpdateBlockFunc_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBlockFunc",
			Handler:       _Tracker_ListBlockFunc_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/tracker/v1/tracker.proto",
}
