// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-server/internal/conf"
	"go-server/internal/data"
	"go-server/internal/server"
	"go-server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.InitDatabase(confData)
	trackerRepo := data.NewTrackerRepo(db, logger)
	trackerService := service.NewTrackerService(trackerRepo)
	grpcServer := server.NewGRPCServer(confServer, trackerService, logger)
	httpServer := server.NewHTTPServer(confServer, trackerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
